In [3]:
import pandas as pd     #(version 1.0.0)
import plotly           #(version 4.5.4) #pip install plotly==4.5.4
import plotly.express as px
import plotly.io as pio

In [ ]:
url = 'NYPD_Arrest_Data.csv'
df = pd.read_csv(url)
df

In [5]:
df['ARREST_DATE'] = pd.to_datetime(df['ARREST_DATE'])

In [6]:
day_name = df['ARREST_DATE'].dt.day_name()

In [7]:
df.insert(2,'WEEKDAY',day_name)

In [8]:
df

,ARREST_KEY,ARREST_DATE,WEEKDAY,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,234233843,2021-09-29,Wednesday,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,B,42,0,25-44,M,BLACK,1009231,240290,40.826189,-73.909738,POINT (-73.90973778899996 40.82618898100003)
1,234129823,2021-09-27,Monday,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,K,77,0,25-44,M,BLACK,1003606,185050,40.674583,-73.930222,POINT (-73.93022154099998 40.67458330800008)
2,234040747,2021-09-25,Saturday,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,Q,101,0,25-44,M,BLACK,1049232,159210,40.603441,-73.765986,POINT (-73.76598558899997 40.60344094100003)
3,234047720,2021-09-25,Saturday,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1006537,244511,40.837782,-73.919458,POINT (-73.91945797099999 40.83778161800007)
4,234042526,2021-09-25,Saturday,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1007418,243859,40.835990,-73.916276,POINT (-73.91627635999998 40.83598980000005)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115294,222689440,2021-01-06,Wednesday,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,Q,102,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031076,193779,40.698440,-73.831130,POINT (-73.83112953899997 40.69843969400005)
115295,222626401,2021-01-05,Tuesday,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,B,49,0,25-44,M,BLACK HISPANIC,1027430,251105,40.855803,-73.843910,POINT (-73.84390995399998 40.85580274300003)
115296,222477062,2021-01-01,Friday,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL0511001,M,B,50,0,25-44,M,WHITE HISPANIC,1011047,256269,40.870041,-73.903112,POINT (-73.90311219699998 40.870041281000056)
115297,222728174,2021-01-07,Thursday,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,M,Q,114,0,25-44,M,WHITE HISPANIC,1007694,219657,40.769561,-73.915363,POINT (-73.91536344699995 40.76956124200007)
115298,222535613,2021-01-03,Sunday,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 265031B,F,K,67,0,25-44,M,BLACK,1000054,173952,40.644129,-73.943053,POINT (-73.94305278599995 40.64412879400004)

In [9]:
df.rename(columns= {'WEEKDAY':'DAY_OF_THE_WEEK'},inplace = True)
df

,ARREST_KEY,ARREST_DATE,DAY_OF_THE_WEEK,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,234233843,2021-09-29,Wednesday,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,B,42,0,25-44,M,BLACK,1009231,240290,40.826189,-73.909738,POINT (-73.90973778899996 40.82618898100003)
1,234129823,2021-09-27,Monday,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,K,77,0,25-44,M,BLACK,1003606,185050,40.674583,-73.930222,POINT (-73.93022154099998 40.67458330800008)
2,234040747,2021-09-25,Saturday,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,Q,101,0,25-44,M,BLACK,1049232,159210,40.603441,-73.765986,POINT (-73.76598558899997 40.60344094100003)
3,234047720,2021-09-25,Saturday,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1006537,244511,40.837782,-73.919458,POINT (-73.91945797099999 40.83778161800007)
4,234042526,2021-09-25,Saturday,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1007418,243859,40.835990,-73.916276,POINT (-73.91627635999998 40.83598980000005)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115294,222689440,2021-01-06,Wednesday,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,Q,102,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031076,193779,40.698440,-73.831130,POINT (-73.83112953899997 40.69843969400005)
115295,222626401,2021-01-05,Tuesday,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,B,49,0,25-44,M,BLACK HISPANIC,1027430,251105,40.855803,-73.843910,POINT (-73.84390995399998 40.85580274300003)
115296,222477062,2021-01-01,Friday,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL0511001,M,B,50,0,25-44,M,WHITE HISPANIC,1011047,256269,40.870041,-73.903112,POINT (-73.90311219699998 40.870041281000056)
115297,222728174,2021-01-07,Thursday,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,M,Q,114,0,25-44,M,WHITE HISPANIC,1007694,219657,40.769561,-73.915363,POINT (-73.91536344699995 40.76956124200007)
115298,222535613,2021-01-03,Sunday,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 265031B,F,K,67,0,25-44,M,BLACK,1000054,173952,40.644129,-73.943053,POINT (-73.94305278599995 40.64412879400004)

In [10]:
month = df['ARREST_DATE'].dt.strftime('%B')

In [11]:
df.insert(3,'MONTH',month)

In [12]:
df

,ARREST_KEY,ARREST_DATE,DAY_OF_THE_WEEK,MONTH,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,...,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,234233843,2021-09-29,Wednesday,September,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,...,42,0,25-44,M,BLACK,1009231,240290,40.826189,-73.909738,POINT (-73.90973778899996 40.82618898100003)
1,234129823,2021-09-27,Monday,September,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,...,77,0,25-44,M,BLACK,1003606,185050,40.674583,-73.930222,POINT (-73.93022154099998 40.67458330800008)
2,234040747,2021-09-25,Saturday,September,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,...,101,0,25-44,M,BLACK,1049232,159210,40.603441,-73.765986,POINT (-73.76598558899997 40.60344094100003)
3,234047720,2021-09-25,Saturday,September,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,...,44,0,25-44,M,BLACK,1006537,244511,40.837782,-73.919458,POINT (-73.91945797099999 40.83778161800007)
4,234042526,2021-09-25,Saturday,September,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,...,44,0,25-44,M,BLACK,1007418,243859,40.835990,-73.916276,POINT (-73.91627635999998 40.83598980000005)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115294,222689440,2021-01-06,Wednesday,January,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,...,102,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031076,193779,40.698440,-73.831130,POINT (-73.83112953899997 40.69843969400005)
115295,222626401,2021-01-05,Tuesday,January,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,...,49,0,25-44,M,BLACK HISPANIC,1027430,251105,40.855803,-73.843910,POINT (-73.84390995399998 40.85580274300003)
115296,222477062,2021-01-01,Friday,January,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL0511001,M,...,50,0,25-44,M,WHITE HISPANIC,1011047,256269,40.870041,-73.903112,POINT (-73.90311219699998 40.870041281000056)
115297,222728174,2021-01-07,Thursday,January,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,M,...,114,0,25-44,M,WHITE HISPANIC,1007694,219657,40.769561,-73.915363,POINT (-73.91536344699995 40.76956124200007)
115298,222535613,2021-01-03,Sunday,January,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 265031B,F,...,67,0,25-44,M,BLACK,1000054,173952,40.644129,-73.943053,POINT (-73.94305278599995 40.64412879400004)

In [13]:
day = df['ARREST_DATE'].dt.day

In [14]:
df.insert(4,'DAY',day)

In [15]:
df

,ARREST_KEY,ARREST_DATE,DAY_OF_THE_WEEK,MONTH,DAY,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,...,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,234233843,2021-09-29,Wednesday,September,29,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,...,42,0,25-44,M,BLACK,1009231,240290,40.826189,-73.909738,POINT (-73.90973778899996 40.82618898100003)
1,234129823,2021-09-27,Monday,September,27,157.0,RAPE 1,104.0,RAPE,PL 1303501,...,77,0,25-44,M,BLACK,1003606,185050,40.674583,-73.930222,POINT (-73.93022154099998 40.67458330800008)
2,234040747,2021-09-25,Saturday,September,25,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,...,101,0,25-44,M,BLACK,1049232,159210,40.603441,-73.765986,POINT (-73.76598558899997 40.60344094100003)
3,234047720,2021-09-25,Saturday,September,25,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,...,44,0,25-44,M,BLACK,1006537,244511,40.837782,-73.919458,POINT (-73.91945797099999 40.83778161800007)
4,234042526,2021-09-25,Saturday,September,25,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,...,44,0,25-44,M,BLACK,1007418,243859,40.835990,-73.916276,POINT (-73.91627635999998 40.83598980000005)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115294,222689440,2021-01-06,Wednesday,January,6,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,...,102,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031076,193779,40.698440,-73.831130,POINT (-73.83112953899997 40.69843969400005)
115295,222626401,2021-01-05,Tuesday,January,5,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,...,49,0,25-44,M,BLACK HISPANIC,1027430,251105,40.855803,-73.843910,POINT (-73.84390995399998 40.85580274300003)
115296,222477062,2021-01-01,Friday,January,1,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL0511001,...,50,0,25-44,M,WHITE HISPANIC,1011047,256269,40.870041,-73.903112,POINT (-73.90311219699998 40.870041281000056)
115297,222728174,2021-01-07,Thursday,January,7,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,...,114,0,25-44,M,WHITE HISPANIC,1007694,219657,40.769561,-73.915363,POINT (-73.91536344699995 40.76956124200007)
115298,222535613,2021-01-03,Sunday,January,3,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 265031B,...,67,0,25-44,M,BLACK,1000054,173952,40.644129,-73.943053,POINT (-73.94305278599995 40.64412879400004)

In [16]:
df['MONTH_AS_NUMBER'] = pd.DatetimeIndex(df['ARREST_DATE']).month

In [17]:
df

,ARREST_KEY,ARREST_DATE,DAY_OF_THE_WEEK,MONTH,DAY,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,...,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column,MONTH_AS_NUMBER
0,234233843,2021-09-29,Wednesday,September,29,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,...,0,25-44,M,BLACK,1009231,240290,40.826189,-73.909738,POINT (-73.90973778899996 40.82618898100003),9
1,234129823,2021-09-27,Monday,September,27,157.0,RAPE 1,104.0,RAPE,PL 1303501,...,0,25-44,M,BLACK,1003606,185050,40.674583,-73.930222,POINT (-73.93022154099998 40.67458330800008),9
2,234040747,2021-09-25,Saturday,September,25,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,...,0,25-44,M,BLACK,1049232,159210,40.603441,-73.765986,POINT (-73.76598558899997 40.60344094100003),9
3,234047720,2021-09-25,Saturday,September,25,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,...,0,25-44,M,BLACK,1006537,244511,40.837782,-73.919458,POINT (-73.91945797099999 40.83778161800007),9
4,234042526,2021-09-25,Saturday,September,25,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,...,0,25-44,M,BLACK,1007418,243859,40.835990,-73.916276,POINT (-73.91627635999998 40.83598980000005),9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115294,222689440,2021-01-06,Wednesday,January,6,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,...,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031076,193779,40.698440,-73.831130,POINT (-73.83112953899997 40.69843969400005),1
115295,222626401,2021-01-05,Tuesday,January,5,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,...,0,25-44,M,BLACK HISPANIC,1027430,251105,40.855803,-73.843910,POINT (-73.84390995399998 40.85580274300003),1
115296,222477062,2021-01-01,Friday,January,1,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL0511001,...,0,25-44,M,WHITE HISPANIC,1011047,256269,40.870041,-73.903112,POINT (-73.90311219699998 40.870041281000056),1
115297,222728174,2021-01-07,Thursday,January,7,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,...,0,25-44,M,WHITE HISPANIC,1007694,219657,40.769561,-73.915363,POINT (-73.91536344699995 40.76956124200007),1
115298,222535613,2021-01-03,Sunday,January,3,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 265031B,...,0,25-44,M,BLACK,1000054,173952,40.644129,-73.943053,POINT (-73.94305278599995 40.64412879400004),1

In [18]:
df['WEEKDAY_AS_NUMBER'] = df['ARREST_DATE'].dt.dayofweek

In [19]:
pd.set_option('display.max_columns', None)

In [20]:
df

,ARREST_KEY,ARREST_DATE,DAY_OF_THE_WEEK,MONTH,DAY,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column,MONTH_AS_NUMBER,WEEKDAY_AS_NUMBER
0,234233843,2021-09-29,Wednesday,September,29,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,B,42,0,25-44,M,BLACK,1009231,240290,40.826189,-73.909738,POINT (-73.90973778899996 40.82618898100003),9,2
1,234129823,2021-09-27,Monday,September,27,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,K,77,0,25-44,M,BLACK,1003606,185050,40.674583,-73.930222,POINT (-73.93022154099998 40.67458330800008),9,0
2,234040747,2021-09-25,Saturday,September,25,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,Q,101,0,25-44,M,BLACK,1049232,159210,40.603441,-73.765986,POINT (-73.76598558899997 40.60344094100003),9,5
3,234047720,2021-09-25,Saturday,September,25,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1006537,244511,40.837782,-73.919458,POINT (-73.91945797099999 40.83778161800007),9,5
4,234042526,2021-09-25,Saturday,September,25,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,0,25-44,M,BLACK,1007418,243859,40.835990,-73.916276,POINT (-73.91627635999998 40.83598980000005),9,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115294,222689440,2021-01-06,Wednesday,January,6,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,Q,102,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031076,193779,40.698440,-73.831130,POINT (-73.83112953899997 40.69843969400005),1,2
115295,222626401,2021-01-05,Tuesday,January,5,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,B,49,0,25-44,M,BLACK HISPANIC,1027430,251105,40.855803,-73.843910,POINT (-73.84390995399998 40.85580274300003),1,1
115296,222477062,2021-01-01,Friday,January,1,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL0511001,M,B,50,0,25-44,M,WHITE HISPANIC,1011047,256269,40.870041,-73.903112,POINT (-73.90311219699998 40.870041281000056),1,4
115297,222728174,2021-01-07,Thursday,January,7,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,M,Q,114,0,25-44,M,WHITE HISPANIC,1007694,219657,40.769561,-73.915363,POINT (-73.91536344699995 40.76956124200007),1,3
115298,222535613,2021-01-03,Sunday,January,3,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 265031B,F,K,67,0,25-44,M,BLACK,1000054,173952,40.644129,-73.943053,POINT (-73.94305278599995 40.64412879400004),1,6

In [21]:
df.dtypes

ARREST_KEY                           int64
ARREST_DATE                 datetime64[ns]
DAY_OF_THE_WEEK                     object
MONTH                               object
DAY                                  int64
PD_CD                              float64
PD_DESC                             object
KY_CD                              float64
OFNS_DESC                           object
LAW_CODE                            object
LAW_CAT_CD                          object
ARREST_BORO                         object
ARREST_PRECINCT                      int64
JURISDICTION_CODE                    int64
AGE_GROUP                           object
PERP_SEX                            object
PERP_RACE                           object
X_COORD_CD                           int64
Y_COORD_CD                           int64
Latitude                           float64
Longitude                          float64
New Georeferenced Column            object
MONTH_AS_NUMBER                      int64
WEEKDAY_AS_NUMBER                    int64
dtype: object

In [22]:
df_group = df.groupby(['ARREST_DATE'])

In [23]:
df_crime_and_DayofWeek = df.groupby(['DAY_OF_THE_WEEK','OFNS_DESC']).count()

In [24]:
type(df_crime_and_DayofWeek )

pandas.core.frame.DataFrame

In [26]:
extra = df.groupby(['DAY_OF_THE_WEEK','OFNS_DESC','AGE_GROUP','ARREST_BORO']).count().head(50)

In [27]:
Brooklyn_df = df[df['ARREST_BORO']=='K']

In [28]:
Brooklyn_df_group = Brooklyn_df.groupby(['DAY_OF_THE_WEEK','OFNS_DESC','AGE_GROUP'],as_index = False)['PERP_RACE'].sum()

In [29]:
Brooklyn_df2 = df[df['ARREST_BORO']=='K']

In [30]:
Brooklyn_df2.groupby(['DAY_OF_THE_WEEK','PERP_SEX','OFNS_DESC'],as_index = False)[['AGE_GROUP','PERP_RACE']].sum()

,DAY_OF_THE_WEEK,PERP_SEX,OFNS_DESC,AGE_GROUP,PERP_RACE
0,Friday,F,ADMINISTRATIVE CODE,45-64,WHITE HISPANIC
1,Friday,F,AGRICULTURE & MRKTS LAW-UNCLASSIFIED,18-24,ASIAN / PACIFIC ISLANDER
2,Friday,F,ALCOHOLIC BEVERAGE CONTROL LAW,25-4445-6425-4425-44,ASIAN / PACIFIC ISLANDERBLACKBLACKBLACK
3,Friday,F,ANTICIPATORY OFFENSES,25-44,WHITE
4,Friday,F,ARSON,18-24,BLACK HISPANIC
...,...,...,...,...,...
560,Wednesday,M,SEX CRIMES,25-44<1818-2425-4445-6418-2445-6445-6425-4445-...,WHITEBLACKWHITE HISPANICBLACKBLACKWHITE HISPAN...
561,Wednesday,M,THEFT OF SERVICES,25-4418-24,WHITE HISPANICBLACK
562,Wednesday,M,THEFT-FRAUD,25-4425-4418-24,BLACKBLACKBLACK
563,Wednesday,M,UNAUTHORIZED USE OF A VEHICLE,45-6418-2425-4425-4425-4418-2425-4425-4418-242...,BLACKBLACKBLACKBLACKBLACK HISPANICWHITE HISPAN...
564,Wednesday,M,VEHICLE AND TRAFFIC LAWS,18-2418-2425-4418-2425-4418-2425-4425-4445-644...,BLACKBLACKWHITE HISPANICBLACKWHITEWHITEBLACKAS...

In [31]:
Brooklyn_df2.groupby(['DAY_OF_THE_WEEK','AGE_GROUP'],as_index = False)[['OFNS_DESC']].count()

   DAY_OF_THE_WEEK AGE_GROUP  OFNS_DESC
0           Friday     18-24        944
1           Friday     25-44       2514
2           Friday     45-64        806
3           Friday       65+         58
4           Friday       <18        183
5           Monday     18-24        671
6           Monday     25-44       2171
7           Monday     45-64        662
8           Monday       65+         52
9           Monday       <18        125
10        Saturday     18-24        755
11        Saturday     25-44       2157
12        Saturday     45-64        644
13        Saturday       65+         49
14        Saturday       <18        134
15          Sunday     18-24        737
16          Sunday     25-44       2098
17          Sunday     45-64        577
18          Sunday       65+         49
19          Sunday       <18         94
20        Thursday     18-24       1005
21        Thursday     25-44       2920
22        Thursday     45-64       1059
23        Thursday       65+         79
24        Thursday       <18        187
25         Tuesday     18-24        991
26         Tuesday     25-44       2786
27         Tuesday     45-64        935
28         Tuesday       65+         77
29         Tuesday       <18        174
30       Wednesday     18-24       1116
31       Wednesday     25-44       2982
32       Wednesday     45-64        952
33       Wednesday       65+         72
34       Wednesday       <18        173

In [32]:
bk_groupby_2 = Brooklyn_df2.groupby(['DAY_OF_THE_WEEK','AGE_GROUP'],as_index = False)[['OFNS_DESC']].count()

In [34]:
bk_groupby_2.rename(columns={'OFNS_DESC':'NUMBER_OF_OFFENDERS'},inplace=True)

In [40]:
barchart = px.bar(
    data_frame=bk_groupby_2,
    x="DAY_OF_THE_WEEK",
    y="NUMBER_OF_OFFENDERS",
    color="AGE_GROUP",               # differentiate color of marks
    opacity=0.9,                  # set opacity of markers (from 0 to 1)
    orientation="v",              # 'v','h': orientation of the marks
    barmode='relative',           # in 'overlay' mode, bars are top of one another.
                                  # in 'group' mode, bars are placed beside each other.
                                  # in 'relative' mode, bars are stacked above (+) or below (-) zero.
    #----------------------------------------------------------------------------------------------
    # facet_row='caste',          # assign marks to subplots in the vertical direction
    # facet_col='caste',          # assigns marks to subplots in the horizontal direction
    # facet_col_wrap=2,           # maximum number of subplot columns. Do not set facet_row!

    # color_discrete_sequence=["pink","yellow"],               # set specific marker colors. Color-colum data cannot be numeric
    # color_discrete_map={"Male": "gray" ,"Female":"red"},     # map your chosen colors
    # color_continuous_scale=px.colors.diverging.Picnic,       # set marker colors. When color colum is numeric data
    # color_continuous_midpoint=100,                           # set desired midpoint. When colors=diverging
    # range_color=[1,10000],                                   # set your own continuous color scale
    #----------------------------------------------------------------------------------------------
    # text='convicts',            # values appear in figure as text labels
    # hover_name='under_trial',   # values appear in bold in the hover tooltip
    # hover_data=['detenues'],    # values appear as extra data in the hover tooltip
    # custom_data=['others'],     # invisible values that are extra data to be used in Dash callbacks or widgets

    # log_x=True,                 # x-axis is log-scaled
    # log_y=True,                 # y-axis is log-scaled
    # error_y="err_plus",         # y-axis error bars are symmetrical or for positive direction
    # error_y_minus="err_minus",  # y-axis error bars in the negative direction

    #labels={"convicts":"Convicts in Maharashtra",
    #"gender":"Gender"},           # map the labels of the figure
    title='Crime by day of the week and age group', # figure title
    width=1400,                   # figure width in pixels
    height=720,                   # figure height in pixels
    template='gridon',            # 'ggplot2', 'seaborn', 'simple_white', 'plotly',
                                  # 'plotly_white', 'plotly_dark', 'presentation',
                                  # 'xgridoff', 'ygridoff', 'gridon', 'none'

    # animation_frame='year',     # assign marks to animation frames
    # # animation_group=,         # use only when df has multiple rows with same object
    # # range_x=[5,50],           # set range of x-axis
    # range_y=[0,9000],           # set range of x-axis
    # category_orders={'year':    # force a specific ordering of values per column
    # [2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001]},

)

barchart.show()